fluent/cmetrics

CMakeLists.txt, src/CMakeLists.txt
This is needed for miniportile's cmake building process.
=> Add install target for cmetrics library

scripts/win_build.bat
`-DCMT_TESTS=On` also should be added in scripts/win_build.bat.
=> Ensure to enable cmetrics tests on msvc

src/CMakeLists.txt
CMake v3.10 complains lack of ARCHIVE and LIBRARY destinations....
I'd overlooked this issue.
=> build: Specify ARCHIVE and LIBRARY destinations to be able to built w/ CMAKE 3.10

CMakeLists.txt, include/CMakeLists.txt, lib/monkey/include/CMakeLists.txt
Headers are also needed as install targets.
This is also needed for miniportile's cmake building process.
=> Add headers as install targets

CMakeLists.txt
CMake v3.10 does not specify this flag by default.
Ubuntu 18.04 LTS still uses cmake v3.10.
=> Specify position indepentent code flag explicitly

CMakeLists.txt
`mpack` and `xxhash` installations should be configurable due to bundling into fluent-bit.
fluent-bit is already bundled them in itself.
=> Add CMT_INSTALL_TARGETS option to handle subdirectory library installations

.github/workflows/packages.yaml
* build deb/rpm packages for library/headers and store them on the action artifacts.
=> workflows: add package build/store for deb/rpm.

include/cmetrics/cmt_compat.h, src/cmt_encode_text.c
This is because downstream Ruby binding does not know how to handle `CMT_HAVE_GMTIME_S` constant which is defined by cmake.
This compatibility layer should be separated from main headers.
=> compat: build: Extract Windows compatibility layer function to cmt_compat.h

include/cmetrics/cmt_compat.h, lib/monkey/include/monkey/mk_core/mk_list.h, src/cmetrics.c, src/cmt_decode_msgpack.c, src/cmt_encode_msgpack.c, src/cmt_encode_prometheus.c, src/cmt_log.c, src/cmt_map.c
On cmetrics itself, it does not cause undeclared identifier problems due to mk_list.h includes `<windows.h>`.
But, bundled cmetrics on fluent-bit causes these issues because fluent-bit bundled mk_list.h does not include windows.h.
This header definition glitch causes building failure at fluent-bit.
=> Include windows.h on  win32 environment explicitly and unify mk_list.h definition from fluent-bit uses one

include/cmetrics/cmt_compat.h, src/cmt_encode_text.c
This is because fluent-bit is already provided similiar function on its compat layer.
Ruby is also provided its gmtime_s|r wrapper in ruby.h.
We should use `cmt_platform_` prefix to wrap `gmtime_s` and `gmtime_r` functions.
And I fixed `#ifdef CMT_HAVE_GMTIME_S` from `#if CMT_HAVE_GMTIME_S`, too.
=> compat: encode_text: Use cmt_platform prefix-ed gmtime_r|s wrap function

include/cmetrics/cmt_encode_msgpack.h, src/cmt_decode_msgpack.c
msgpack : bumped the encoder version to 2 because of the untyped metric addition
Signed-off-by: Leonardo Almiñana <leonardo@calyptia.com>
=> msgpack: fixed wrong attribution of decoded gauges as counters

src/cmt_encode_prometheus_remote_write.c
=> encoding: prometheus_remote_write: convert ns timestamp to milliseconds

src/cmt_time.c
Found this while compiling fluent-bit 1.8.9
```
...
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
...
../src/cmt_time.c:44:7: error: member reference type 'struct timespec' is not a pointer; did you mean to use '.'?
tm->tv_sec = mts.tv_sec;
~~^~
.
../src/cmt_time.c:44:16: error: expression is not assignable
tm->tv_sec = mts.tv_sec;
~~~~~~~~~~ ^
../src/cmt_time.c:45:7: error: member reference type 'struct timespec' is not a pointer; did you mean to use '.'?
tm->tv_nsec = mts.tv_nsec;
~~^~
.
../src/cmt_time.c:45:17: error: expression is not assignable
tm->tv_nsec = mts.tv_nsec;
~~~~~~~~~~~ ^
4 errors generated.
make[2]: *** [src/CMakeFiles/cmetrics-static.dir/cmt_time.c.o] Error 1
make[1]: *** [src/CMakeFiles/cmetrics-static.dir/all] …
```
=> time: fix compile error on mac

src/cmt_time.c
Fix compilation errors on Darwin (using nixpkgs):
```
[ 16%] Building C object lib/cmetrics/src/CMakeFiles/cmetrics-static.dir/cmt_time.c.o
/tmp/nix-build-fluent-bit-1.8.9.drv-0/source/lib/cmetrics/src/cmt_time.c: In function 'cmt_time_now':
/tmp/nix-build-fluent-bit-1.8.9.drv-0/source/lib/cmetrics/src/cmt_time.c:40:5: error: unknown type name 'clock_serv_t'
40 |     clock_serv_t cclock;
|     ^~~~~~~~~~~~
/tmp/nix-build-fluent-bit-1.8.9.drv-0/source/lib/cmetrics/src/cmt_time.c:41:5: error: unknown type name 'mach_timespec_t'
41 |     mach_timespec_t mts;
|     ^~~~~~~~~~~~~~~
/tmp/nix-build-fluent-bit-1.8.9.drv-0/source/lib/cmetrics/src/cmt_time.c:42:5: warning: implicit declaration of function 'host_get_clock_service' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimp …
```
=> time: fixed CMT_HAVE_CLOCK_GET_TIME macro name 

.github/dependabot.yml, .github/workflows/packages.yaml
Automatically creates a release now when a tag is pushed, the release will contain the RPM or DEB packages as well.
The URL for a release is much easier to consume.
Modified to create a special "unstable" release on every push that contains the built packages so you can have a fixed URL consuming latest.
=> workflows: added upload and auto-release creation

.github/workflows/packages.yaml
Per comment on #59, ensure we only release on a v* tag.
=> workflows: update tag regex for release

.github/workflows/packages.yaml
Tried to trigger a release with a new tag but failed.
The regex needed quoting.
Added workflow dispatch so we can actually select a tag to create a release from as well manually.
=> workflows: quote the regex for tag detection

.github/workflows/build.yaml, CMakeLists.txt, include/cmetrics/cmt_decode_prometheus.h, src/CMakeLists.txt, src/cmt_decode_prometheus.c, src/cmt_decode_prometheus.l, src/cmt_decode_prometheus.y, tests/CMakeLists.txt, tests/prometheus_lexer.c, tests/prometheus_parser.c
Opening the PR for anyone that wants to start reviewing the overall design, but still WIP. Here's what is still missing:
=> Prometheus text format parser

include/cmetrics/cmt_decode_prometheus.h, src/cmt_decode_prometheus.c, src/cmt_decode_prometheus.l, src/cmt_decode_prometheus.y, tests/prometheus_parser.c
- Modify prometheus decode API to receive opts struct which encapsulates errbuf/errbuf_size
- Add default_timestamp option
@edsiper the reason I added a default_timestamp option (instead of calling `cmt_time_now()` directly when parsing) is that it is more flexible and allows easier testing. I've added a test example, but you can use current scrape timestamp like this:
```C
const char *inbuf = ...;
struct cmt *cmt;
struct cmt_decode_prometheus_parse_opts opts = {
.errbuf = NULL,
.default_timestamp = cmt_time_now()
};
cmt_decode_prometheus_create(&cmt, inbuf, &opts);
```
This API change will also make it easier customize parsing in the future without breaking existing callers.
fix #67
=> Allow passing a default timestamp to prometheus decode API

.github/workflows/build.yaml
Resolves #75 by adding build check for CentOS 7.
Note that this fails the actual check because of #74.
We only do a quick build during CI, we are not detaining any packages built.
=> workflows: centos7 build

include/cmetrics/cmt_decode_prometheus.h
macOS's toolchain should be failed with implicit declaration of yylex entity function.
We should declare it explicitly for preventing implicit declaration error.
Fixes #78.
=> Plug an implicit function warning for lex

src/cmt_encode_prometheus.c, tests/encoding.c, tests/prometheus_parser.c
Fix prometheus encoder to escape special characters in HELP description and label values.
=> encode: prometheus: Handle escaping of special characters

include/cmetrics/cmt_histogram.h, src/cmt_histogram.c
This API is necessary to programatically create `cmt_histogram_buckets` (such as when decoding prometheus input)
=> histogram: Add API to create buckets from array

include/cmetrics/cmt_decode_msgpack.h, include/cmetrics/cmt_mpack_utils.h, src/cmt_decode_msgpack.c, src/cmt_encode_msgpack.c, src/cmt_mpack_utils.c, tests/encoding.c
This PR adds histogram support to the msgpack encoder/decoder pair, both `cmt_msgpack` and `cmt_msgpack_cleanup_on_error` are can be executed under valgrind to verify the encoder/decoder pair do not leak.
=> msgpack: histogram support addition

include/cmetrics/cmt_decode_msgpack.h, src/cmt_decode_msgpack.c, src/cmt_encode_msgpack.c, tests/encoding.c
tests: encoding: added a summary to the test data generator
=> msgpack: added summary support in the encoder and decoder

.github/workflows/build.yaml, .github/workflows/packages.yaml
- build using run-on-arch action, this has to be switched
into a base build container that does aarch64 binary emulation or its own
runner.
- store the aarch64 artifacts
Signed-off-by: Jorge Niedbalski <j@calyptia.com>
=> build on aarch64.

include/cmetrics/cmt_decode_prometheus.h, src/cmt_decode_prometheus.c, tests/prometheus_parser.c
Adds summary support to prometheus decoder.
Note: Since cmetrics API doesn't allow setting "quantile" label values, they are ignored when parsing (as shown in the added test).
Also removed the option to skip unsupported type, since we now support all types of metrics.
=> decode: prometheus: Add Summary support

include/cmetrics/cmt_decode_prometheus.h, src/cmt_decode_prometheus.c, src/cmt_encode_prometheus.c, tests/null_label.c, tests/prometheus_parser.c
This PR fixes a problem with prometheus encoding when labels are NULL. Also enables support on decoder.
=> Prometheus decoder support null labels

src/cmt_encode_opentelemetry.c, tests/encoding.c
There is still one issue, because `cmt_summary` does not have a list of quantile boundaries I had to put dummy values at the moment  in [cmt_encode_opentelemetry.c#L1711](https://github.com/calyptia/cmetrics/blob/e97973dc05b2843cb956efadc15c26cb4b575a94/src/cmt_encode_opentelemetry.c#L1711).
=> encoding: opentelemetry: added histogram and summary support

include/cmetrics/cmt_metric.h, include/cmetrics/cmt_summary.h, src/cmt_decode_prometheus.c, src/cmt_map.c, src/cmt_summary.c, tests/encoding.c, tests/summary.c
the following PR changes the summary creation prototype, not it accepts a number of expected quantiles and it quantile value.
in the _set_default api allows to specify the final value for each quantile
=> summary: fix quantiles api

include/cmetrics/cmt_decode_msgpack.h, src/cmt_decode_msgpack.c, src/cmt_encode_msgpack.c, tests/encoding.c
This PR will seem to leak memory but that's just a bug in `cmt_map_destroy` for which I am preparing another PR right now.
=> encoding: msgpack: added dynamic quantile count support

src/cmt_map.c, tests/encoding.c
Summary quantiles were being properly released for dynamic metrics (samples with labels) but not for static metrics, this fixes PR that.
=> map: free static metric sum_quantiles on destroy

include/cmetrics/cmetrics.h, include/cmetrics/cmt_array.h, include/cmetrics/cmt_decode_opentelemetry.h, include/cmetrics/cmt_histogram.h, include/cmetrics/cmt_kvlist.h, include/cmetrics/cmt_opts.h, include/cmetrics/cmt_variant.h, src/CMakeLists.txt, src/cmetrics.c, src/cmt_array.c, src/cmt_decode_opentelemetry.c, src/cmt_histogram.c, src/cmt_kvlist.c, src/cmt_variant.c
This PR adds a variant type that's required by the opentelemetry system, it's only used to represent the resource tree and instrumentation library data at the moment but it will be used for complex labels when the time comes.
Note : At the moment data points can only have labels that hold primitive values (strings, byte arrays, integers, booleans and floating point numbers). In the future, key value lists and arrays will be supported.
=> decode: opentelemetry: initial commit

CMakeLists.txt, cpack/macos/welcome.txt.cmakein
I got succeeded to build macOS installer package w/ cpack's productbuild generator.
This package can be built with:
```console
$ cd /path/to/cmetrics-workdir/build
$ cmake -DCPACK_GENERATOR=productbuild ..
$ cpack -G productbuild 
```
Then, `cmetrics-<cmetrics version>-(apple|intel).pkg` installer will be generated.
=> macos: cpack: Support productbuild package creation

CMakeLists.txt, src/cmt_decode_opentelemetry.c
This PR fixes a bug in the opentelemetry decoder where metric label counts were not incremented causing the msgpack encoder
to generate incorrect data.
Additionally a dummy help string is used when none is received due to a limitation in cmetrics where metric constructors do not allow empty help strings.
=> decoding: opentelemetry decoder fixes

CMakeLists.txt, src/cmt_decode_msgpack.c, src/cmt_encode_influx.c, src/cmt_encode_msgpack.c, src/cmt_encode_text.c
The text representation for histograms and summaries replaces the value with something like this : 
`{ quantiles = { N=N, N=N, N=N }, count=N, sum=N }`  and `{ buckets = { N=N, N=N, N=N }, count=N, sum=N }` 
As for influxdb, I followed version 1 of the format used to store prometheus metrics because that seemed to be the format we had been using : https://docs.influxdata.com/influxdb/v2.1/reference/prometheus-metrics/
This PR does not include any unit test changes but I was thinking about enhancing the context generated by `generate_encoder_test_data` and using that in all the tests to simplify things. That is what I did to test it while developing but opted not to make the change in the same PR to keep things clean.
=> encoding: influx & text: added histogram and summary support

src/cmt_decode_prometheus.c, src/cmt_decode_prometheus.y, tests/prometheus_parser.c
Allow empty HELP/TYPE sections when parsing prometheus metrics. These empty metrics are just ignored by the parser.
=> decode: prometheus: Support parsing empty metrics

include/cmetrics/cmt_decode_prometheus.h, src/cmt_decode_prometheus.c, src/cmt_decode_prometheus.y, tests/prometheus_parser.c
Here we modify the parser to use an existing summary/histogram instance when a duplicate metric is found.
=> decode: prometheus: Properly handle duplicate summary/histogram

CMakeLists.txt
This option can be useful when building on systems that have broken versions of bison/flex.
=> build: Add option to disable prometheus decoder

scripts/win_build.bat
Note that CFL build still fails due to some missing definitions
=> ci: appveyor: Explicitly invoke `git submodule` from build script

src/cmt_decode_msgpack.c, src/cmt_encode_msgpack.c, src/cmt_encode_opentelemetry.c
This PR fixes a bug that caused static labels to be lost when decoding a msgpack encoded context, additionally, static labels were moved to the global meta->processing section.
There is also a minor fix in the otlp encoder for an uninitialized variable access.
=> encoding: msgpack: fixed missing static labels bug

src/cmt_decode_prometheus.c
See https://github.com/calyptia/cmetrics/pull/117
Most probably this change missed from original PR, because value of 'timestamp' was never been used in `add_metric_histogram`
cc @leonardo-albertovich
=> Add missing timestamp on histogram

CMakeLists.txt
- Flex and bison are installed in version 2 by default, brew has newer versions.
Signed-off-by: Jorge Niedbalski <j@calyptia.com>
=> Try to get dependencies using brew paths.

src/cmt_encode_opentelemetry.c
=> encoding: opentelemetry: fixed typo that caused concurrency problems.

src/cmt_encode_splunk_hec.c, tests/encoding.c
For example, 1e+10 is not valid form for Splunk.
Instead, we have to use 1.0e+10 or more zeroed format such as 1.000000e+10 is valid for Splunk metrics.
=> encoding: splunk_hec: Use scientific form on exponential format

include/cmetrics/cmt_decode_msgpack.h, src/cmt_counter.c, src/cmt_decode_msgpack.c, src/cmt_encode_msgpack.c
The goal is to store the aggregation type when encoding in msgpack format.
This will fix this issue: https://github.com/fluent/fluent-bit/issues/6303
=> feat: store aggregation type

include/cmetrics/cmt_decode_msgpack.h, include/cmetrics/cmt_metric.h, src/cmt_decode_msgpack.c, src/cmt_decode_opentelemetry.c, src/cmt_summary.c
Remove the self-imposed limit of 5 quantile summaries, re #167. This causes a bug when decoding prometheus metrics.
=> decode: remove summary quantile limit.

src/cmt_decode_prometheus.c, tests/data/histogram_different_label_count.txt, tests/prometheus_parser.c
Since cmt_map does not allow different label count when fetching metrics, we create a different cmt_histogram/cmt_summary when the label count is different.
=> decode: prometheus: Fix when consecutive metrics have differnet label count

src/cmt_decode_msgpack.c, src/cmt_encode_msgpack.c
This code fixes a bug in the msgpack encoder that caused a crash when trying to encode histograms with no buckets set up.
This happened when ingesting an opentelemetry packet with an empty histogram such as this : 
```
metrics {
name: "http.client.duration"
description: "measures the duration of the outbound HTTP requests"
unit: "ms"
histogram {
aggregation_temporality: AGGREGATION_TEMPORALITY_CUMULATIVE
}
}
```
With this patch the msgpack encoder will not try to dereference the `buckets` member to create the array when the histogram has not been set up and the msgpack decoder will handle the use case properly as well (as it previously expected the bucket count to be higher than zero).
Acknowledgement : Thanks Henrik Rexed for reporting the bug and providing the information necessary to …
=> decode: msgpack empty histogram fix

CMakeLists.txt, src/cmt_encode_opentelemetry.c
This PR makes the opentelemetry encoder promote untyped metrics to gauges instead of sums to overcome an issue reported by Ignacio Coterillo.
=> encoding: opentelemetry: switched the type untyped metrics are casted to

src/cmt_decode_msgpack.c
Found by a recently added fuzzer.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=61743
=> decode: fix possible NULL dereference

include/cmetrics/cmt_cat.h, include/cmetrics/cmt_filter.h, src/CMakeLists.txt, src/cmt_cat.c, src/cmt_filter.c, tests/CMakeLists.txt, tests/filter.c
I implemented filtering mechanism which is mainly targeted for full qualified name of metrics (fqname).
Maybe, we need to implement filtering mechanism for label values but traversing values of labels are more complex rather than just searching with keys of labels.
Also, cmetrics should provide a capability to inject external callback function which uses Onigmo contexts that are mainly used in filter_grep or perhaps processor_grep?
=> Implement filtering mechanism for cmetrics context

include/cmetrics/cmt_math.h
This PR aims to address some issues presented in Fluent Bit repo:
- https://github.com/fluent/fluent-bit/issues/8083
- https://github.com/fluent/fluent-bit/pull/8762
Note that internally we store everything as uint64_t, to deal with floating point numbers we need to avoid losing precision, so this PR consider changes by using memcpy() when storing data.
Other pending thing, we need decide how to handle NaN and Inf values (encoding/decoding)
=> math: simplify types conversion 

include/cmetrics/cmt_cat.h, include/cmetrics/cmt_filter.h, include/cmetrics/cmt_map.h, src/cmt_cat.c, src/cmt_filter.c, src/cmt_map.c, tests/filter.c
Otel collector supports _delete by label value_ operation which means deleting metrics' data points by matched label key-value pair.
This patch makes to be able to handle label key-value based metrics deletions. And also it is intended to use processor_metrics_selector.
=> filter: Implement deleting by label key-value pair operation

src/cmt_decode_prometheus.c
This one's an absolute corker. Windows (even 64-bit!) uses an LLP64 data model where `long int` is still only 32-bits... so timestamp values in the Prometheus text exposition format (which are 64-bit ints by spec) greater than 2^32 do not get parsed correctly on Windows, because `strtol` parses to that 32-bit `long` :))) .
See: https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models .
On my 64-bit Linux, `int64_t` is `long`, but as best I can tell, casting `long long` to `long` is fine / a no-op there, given they are both 64-bit on that platform. If a more considered `sizeof(long long)` check is better I can do that instead but I figured it was probably overkill.
=> decode_prometheus: fix 64-bit timestamp parsing for Windows

src/cmt_encode_influx.c, tests/encoding.c
This issue is reported in
https://github.com/fluent/fluent-bit/issues/9238.
=> encode_influx: Handle no namespace case

src/cmt_decode_msgpack.c
Fixes the following issue detected by OSS-Fuzz:
- https://issues.oss-fuzz.com/issues/371659893
This fix was generated by CodeRover-S, an LLM agent for fixing security vulnerabilities. More details can be found at:
- https://arxiv.org/pdf/2411.03346
- https://github.com/AutoCodeRoverSG/auto-code-rover
=> decode: msgpack: fix NULL dereference
