- include/cmetrics/cmt_decode_msgpack.h
- include/cmetrics/cmt_encode_msgpack.h
- include/cmetrics/cmt_mpack_utils.h
- include/cmetrics/cmt_sds.h
- src/CMakeLists.txt
- src/cmt_decode_msgpack.c
- src/cmt_encode_msgpack.c
- src/cmt_mpack_utils.c
- tests/counter.c
I'm still verifying the cleanup and error handling bits but overall this is how it's going to work.
> Msgpack encoder

- CMakeLists.txt
> build: Install mpack.h when CMT_INSTALL_TARGETS=On

- src/cmt_decode_msgpack.c
Signed-off-by: Leonardo Almiñana <leonardo@calyptia.com>
> msgpack: fixed the wrongfuly initialized metric_static_set flag.

- .github/workflows/build.yaml
> workflows: add windows-2019

- appveyor.yml
- include/cmetrics/cmetrics.h
- scripts/win_build.bat
- src/cmetrics.c
- src/cmt_atomic_clang.c
- src/cmt_atomic_gcc.c
- src/cmt_atomic_generic.c
- src/cmt_atomic_msvc.c
- tests/CMakeLists.txt
- tests/atomic_operations.c
- tests/counter.c
- tests/encoding.c
- tests/gauge.c
tests: Added tests for the atomic operation layer
Signed-off-by: Leonardo Almiñana <leonardo@calyptia.com>
> atomics: Added a mutex based implementation for win32 targets

- scripts/win_build.bat
Signed-off-by: Leonardo Almiñana <leonardo@calyptia.com>
> workflows: appveyor cmake project path fix.

- src/cmt_encode_prometheus_remote_write.c
> encoding: prometheus_remote_write: warning corrections

- include/cmetrics/cmt_counter.h
- src/cmt_counter.c
Allow counters to be flagged as resettable.
> counter: allow counters that can be reset.

- .github/workflows/packages.yaml
Tidy up by removing unused variable.
Add auto-generated release notes.
> workflows: release creation improvements

- src/cmt_decode_prometheus.c
- tests/CMakeLists.txt
- tests/cmt_tests_config.h.in
- tests/data/issue_71.txt
- tests/prometheus_parser.c
- tests/util.c
fix #71
Also added some test infrastructure to make it easy reading files with sample data
> decode: prometheus: fix leak when `finish_metric` fails

- CMakeLists.txt
- appveyor.yml
- src/CMakeLists.txt
> build: set YY_NO_UNISTD_H on Windows

- CMakeLists.txt
> build: check if Flex and Bison has been found before lookup

- include/cmetrics/cmetrics.h
- include/cmetrics/cmt_histogram.h
- include/cmetrics/cmt_metric.h
- include/cmetrics/cmt_sds.h
- src/CMakeLists.txt
- src/cmetrics.c
- src/cmt_encode_prometheus.c
- src/cmt_histogram.c
- src/cmt_map.c
- src/cmt_metric.c
- src/cmt_metric_histogram.c
- tests/CMakeLists.txt
- tests/histogram.c
> Add support for Histograms

- tests/histogram.c
> tests: histograms: verify buckets, _count and _sum

- src/cmt_decode_msgpack.c
- src/cmt_encode_msgpack.c
> msgpack: moved histogram fields to a sub key in metric

- src/cmt_encode_opentelemetry.c
> encoding: opentelemetry: added dynamic quantile list support

- src/cmt_encode_opentelemetry.c
- tests/CMakeLists.txt
- tests/decoding.c
- tests/encoding.c
Assorted improvements in the encoder and decoder tests.
Improved error handling in the opentelemetry encoder.
> tests: assorted improvements

- src/cmt_decode_prometheus.c
With this change the prometheus decoder processes timestamps for summaries and histograms if they are available or sets the timestamp to the current one at the moment of processing (as done for other data types).
> decode: prometheus: added summary and histogram timestamp processing

- CMakeLists.txt
> build: bumped patch version

- src/cmt_decode_prometheus.c
> decode: prometheus: Fix invalid checking of strchr return value

- .github/actionlint-matcher.json
- .github/workflows/build.yaml
- .github/workflows/lint.yaml
- .mdlrc
- markdownlint.rb
Resolves #133 by ensuring we run unit tests with sanitisers during a PR or other build.
Added linting as well.
> workflows: add analysis tooling

- .github/workflows/lint.yaml
- tests/decoding.c
- tests/null_label.c
Signed-off-by: Eduardo Silva <edsiper@gmail.com>
> tests: fix memory leaks

- src/cmt_decode_opentelemetry.c
- src/cmt_encode_opentelemetry.c
- src/cmt_encode_prometheus_remote_write.c
- src/cmt_metric.c
- src/cmt_metric_histogram.c
Signed-off-by: Eduardo Silva <edsiper@gmail.com>
> core: fix compiler warnings

- include/cmetrics/cmt_decode_prometheus.h
- src/cmt_decode_prometheus.c
- tests/prometheus_parser.c
> decode: prometheus: Add option to allow overriding parsed timestamp

- tests/decoding.c
- tests/encoding.c
- tests/prometheus_parser.c
> tests: fix compiler warnings

- src/cmt_decode_prometheus.c
- tests/prometheus_parser.c
> decode: prometheus: Print expected/result when comparison

- tests/prometheus_parser.c
> tests: prometheus_parser: initialize variables

- .github/workflows/build.yaml
- .github/workflows/packages.yaml
Resolves #146, #147 and #124 .
> workflows: handle unstable failures

- include/cmetrics/cmetrics.h
- include/cmetrics/cmt_decode_msgpack.h
- include/cmetrics/cmt_decode_opentelemetry.h
- include/cmetrics/cmt_encode_opentelemetry.h
- include/cmetrics/cmt_variant_utils.h
- src/CMakeLists.txt
- src/cmetrics.c
- src/cmt_decode_msgpack.c
- src/cmt_decode_opentelemetry.c
- src/cmt_encode_msgpack.c
- src/cmt_encode_opentelemetry.c
- tests/decoding.c
Additionally, this PR updates the msgpack encoder and decoder to improve metadata support.
> otlp: updated the otlp encoder and decoder

- src/cmt_encode_msgpack.c
> encoding: msgpack: debug print removed

- src/cmt_decode_prometheus.c
- tests/data/pr_168.txt
- tests/prometheus_parser.c
@pwhelan detected a prometheus summary parsing issue in #168, this PR fixes it
> Fix duplicate summaries for PR #168

- .github/workflows/packages.yaml
- CMakeLists.txt
- cmake/headers.cmake
- create-submoduled-tarball.sh
> cmake: update to include CFL headers

- src/cmt_decode_prometheus.c
- tests/data/issue_6534.txt
- tests/prometheus_parser.c
Should fix this issue: https://github.com/fluent/fluent-bit/issues/6534
> decode: prometheus: Fix histogram/summaries when count/sum are out of order (fluent bit issue #6534)

- src/cmt_cat.c
- tests/cat.c
Fixes: https://github.com/fluent/cmetrics/issues/178
> cat: Implement to concatenate for histogram/summary contexts

- src/cmt_atomic_msvc.c
This PR fixes architecture detection in windows.
> atomics: fixed architecture detection

- src/cmt_decode_opentelemetry.c
This issue was caught by CIFuzz here:
https://github.com/fluent/fluent-bit/pull/7613
> decode: fix possible NULL dereference

- include/cmetrics/cmt_variant_utils.h
This PR introduces resizable array usage to address the bug reported by test case 5541723127021568.
> core: memory exhaustion bug fix

- src/cmt_decode_opentelemetry.c
Upgrade CFL to the newest version and adjust the API for the breaking changes of variants
> lib: cfl: upgrade to v0.5.0

- .github/workflows/build.yaml
- scripts/win_build.bat
We need to build cmetrics sources on Windows at least...
> build: workflows: Fix broken Windows tests

- .github/workflows/packages.yaml
Fixes https://github.com/fluent/cmetrics/issues/173.
> workflows: Add macOS package creations

- .github/workflows/build.yaml
- .github/workflows/packages.yaml
- CODEOWNERS
Fix up usage of building and packaging.
Removed unsupported macOS 12 runner usage.
Added codeowners.
> ci: add required checks and fix builds

- .github/workflows/build.yaml
- CMakeLists.txt
- src/CMakeLists.txt
- src/cmt_encode_opentelemetry.c
- workflows: use CMake v3.20
- upgrade to CFL v0.6.0
- on OpenTelemetry encoding, set the proper flag to include Histograms `sum` field
- fix allocation of size for `explicit_bounds` must be set using a multiple of `sizeof(double)`
> workflows: update for CMake 3.20 and other fixes

- src/cmt_decode_prometheus.l
Fixes: https://issues.oss-fuzz.com/issues/414728873
> cmt_decode_prometheus.l: fix leak

- src/cmt_decode_opentelemetry.c
Fixes: https://issues.oss-fuzz.com/issues/42531451
> decode: opentelemetry: fix NULL deref
